### PR TITLE
Port 'Drawing Area' demo to Python

### PR DESCRIPTION
**Pull request by rolandlo**
The current implementations are unnecessarily complicated. So I wrote simpler code for the Python implementation. If you agree I can simplify the other implementations accordingly.

### CODE REVIEW

**Comment by rolandlo** [comment]
Another implementation would leave the math for rotation to the cairo context:

```python
import workbench
import math

drawing_area = workbench.builder.get_object("drawing_area")
scale_rotate = workbench.builder.get_object("scale")

triangle = [[100, 100], [0, -100], [-100, 100]]
rotation = 0


def draw(_self, cr, _width, _height):
    # Draw triangle in context
    cr.translate(150, 150)
    cr.rotate(rotation)

    cr.move_to(triangle[2][0], triangle[2][1])
    for vertex in triangle:
        cr.line_to(vertex[0], vertex[1])

    cr.set_source_rgba(1, 0, 1, 1)
    cr.stroke()


def on_rotation_changed(_self):
    global rotation
    rotation = math.radians(scale_rotate.get_value())

    drawing_area.queue_draw()


drawing_area.set_draw_func(draw)
scale_rotate.connect("value-changed", on_rotation_changed)

# https://www.cairographics.org/tutorial/
```

Which one do you prefer?

By the way it would seem more logical to rotate the other way round, but that would change the demo slightly.

**Comment by theCapypara** [comment]
@sonnyp What do you think? The JS demo seems really weird in some places. I added you as reviewer, I'll review the Python demo as-is for now.

**Comment by theCapypara** [comment]
Personally I prefer the second solution you posted above.

**Comment by rolandlo** [comment]
> Feel free to update the JS demo - I remember it to be one of the few we didn't review very carefully

I have updated the JS and Rust demos.

For the Rust implementation I'm not sure if the use of the variable `angle` is optimal. That would have to be checked.

**Review by Hofer-Julian — APPROVED** [review]
The Rust adaption looks good. Thanks, @rolandlo!

I've pushed a commit to your branch with minor changes.

**Review by theCapypara — APPROVED** [review]
Great! Thank you!

**Pull request merged**
