### PR TITLE
Port 'Drop Zone' demo to Python

### PR DESCRIPTION
**Pull request by rolandlo**
The code works fine as far as I can see. I followed the JavaScript version closely. Not sure I'm up to date with the latest code style requirements for Python though. The [styleguide](https://github.com/workbenchdev/demos/blob/main/STYLEGUIDE.md) says nothing about Python.

### CODE REVIEW

**Comment by theCapypara** [comment]
Thanks! I'll have a look soon.

There are no Python guidelines yet, as long as it passes the CI checks it should be fine, as this runs the formatter. Updating the styleguide is planned once we settled on some more rules.

**Comment by rolandlo** [comment]
> Thanks! I'll have a look soon.
> 
> There are no Python guidelines yet, as long as it passes the CI checks it should be fine, as this runs the formatter. Updating the styleguide is planned once we settled on some more rules.

What's your take on unused variables in (callback) functions and lambdas? Should they be named and if so, how?

**Comment by theCapypara** [comment]
That's actually one of the things we haven't settled on yet. How you did it is fine for now. We may go over the demos later and make sure the same style is used everywhere.

**Review by theCapypara — CHANGES_REQUESTED** [review]
In general LGTM and works!
Just one minor code style thing I did notice after all: Can you please use `snake_case` for all function names?

**Comment by theCapypara** [comment]
Thanks again!

**Review by theCapypara — APPROVED** [review]

**Pull request merged**
